Update docs for v1.9.0
pivotal-cf/docs-azure pull request #20
Opened 2018-08-20 07:17 UTC by zhongyi-zhang

2018-08-20 07:17 UTC, zhongyi-zhang commented
@bingosummer could you help to review?

2018-08-20 08:13 UTC, bingosummer requested changes

2018-08-20 08:13 UTC, bingosummer commented on docs-content/release-notes.html.md.erb
> +  * Support update API. You can update service plan to change Redis Cache instance tier. Updating the configuration `enableNonSslPort` is also supported now. See guidance [here](https://github.com/Az
Remove `#183`

2018-08-20 08:22 UTC, zhongyi-zhang commented on docs-content/release-notes.html.md.erb
> +  * Support update API. You can update service plan to change Redis Cache instance tier. Updating the configuration `enableNonSslPort` is also supported now. See guidance [here](https://github.com/Az
Fixed. Thanks for the catch.

2018-08-30 22:32 UTC, merged

2018-08-30 22:32 UTC, jknostman3 commented
@zhongyi-zhang Thanks!